package compiler;

import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;

import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;
import compiler.Lexer.SymbolType;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class Compiler {

    public static void main(String[] args) {

        // Check arguments
        if (args.length < 2) {
            System.err.println("Use: gradle run --args=\"-lexer <file>\"");
            return;
        }

        String mode = args[0];
        String filePath = args[1];

        if (!mode.equals("-lexer")) {
            System.err.println("Unknown mode: " + mode);
            return;
        }

        // Run lexer
        try (Reader reader = new FileReader(filePath)) {

            Lexer lexer = new Lexer(reader);
            Symbol symbol;

            // Print tokens
            do {
                symbol = lexer.getNextSymbol();
                System.out.println(symbol);
            } while (symbol.getType() != SymbolType.EOF);

        } catch (IOException e) {
            System.err.println("IO Error: " + e.getMessage());
        } catch (RuntimeException e) {
            // Lexer errors
            System.err.println("Lexer Error: " + e.getMessage());
        }
    }
}
